In [1]:
from google.colab import files
files.upload(r'C:\Users\A20405224099\Downloads\Multiple Regression\ultimate_student_productivity_dataset_5000.csv')

Saving ultimate_student_productivity_dataset_5000.csv to C:\Users\A20405224099\Downloads\Multiple Regression\ultimate_student_productivity_dataset_5000.csv/ultimate_student_productivity_dataset_5000.csv

{'C:\\Users\\A20405224099\\Downloads\\Multiple Regression\\ultimate_student_productivity_dataset_5000.csv/ultimate_student_productivity_dataset_5000.csv': b'student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,screen_time_hours,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score\n1,18,Other,High School,7.64,1.56,2.2,3.05,2.19,6.52,6.47,81,38,1,0,Good,10,43.05,31.77,73.65,50.16\n2,18,Other,High School,2.21,2.22,2.1,1.65,2.55,5.97,6.05,111,339,0,0,Good,3,15.92,37.0,13.7,1.0\n3,22,Male,High School,3.45,0.0,0.29,1.34,2.08,8.39,7.62,68,266,0,1,Good,8,27.39,34.37,45.15,18.3\n4,17,Other,High School,5.75,2.08,3.01,2.27,2.2,6.31,11.67,113,480,1,1,Poor,3,22.31,77.31,20.92,9.37\n5,19,Other,High School,6.83,1.72,3.33,2.65,0.7,8.01,10.02,121,24,1,0,Good,8,38.11,39.53,59.23,27.81\n6,25,Male,Undergraduate,2.21,3.5,1.69,4.47,1.56,8.34,8.06,110,288,0,1,Average,8,30.52,33.64,36.2,18.53\n7,22,Other,High School,4.6,2.37,1.27,3.12,1.89,7.61,11.34,19,123,1,1,Poor,6,33.26,62.01,37.59,10.35\n8,17,Male,High School,8.77,3.78,2.09,1.76,3.13,7.62,7.27,135,379,1,0,Good,1,31.98,45.98,45.04,19.89\n9,16,Female,Undergraduate,6.6,0.84,1.0,4.39,0.85,8.29,8.24,101,308,1,0,Average,10,30.23,49.44,61.83,30.73\n10,17,Female,High School,3.98,0.16,1.29,3.2,2.13,5.43,7.79,142,415,1,0,Average,9,20.26,60.78,29.06,8.99\n11,25,Other,Postgraduate,2.28,2.69,2.95,3.27,0.6,6.4,4.94,146,24,1,1,Poor,8,19.21,48.25,24.48,11.65\n12,16,Male,High School,5.99,2.6,1.06,0.89,2.72,7.08,7.68,130,157,0,0,Good,2,25.04,36.14,31.13,15.01\n13,16,Other,Postgraduate,4.88,1.65,0.0,3.68,1.39,4.96,8.8,93,193,1,0,Good,10,32.97,51.79,48.33,22.09\n14,25,Other,Undergraduate,5.33,2.07,1.31,3.84,1.63,6.17,10.88,58,298,0,0,Poor,7,31.13,50.49,39.3,22.12\n15,19,Other,Postgraduate,5.31,1.21,0.92,1.97,0.22,7.19,6.94,139,34,0,0,Average,6,31.07,28.0,50.61,29.83\n16,20,Other,Undergraduate,3.85,3.09,3.36,2.13,2.75,5.09,7.39,97,413,0,0,Average,4,21.66,41.97,26.95,14.69\n17,16,Other,Undergraduate,4.91,1.57,2.79,3.34,0.68,8.0,5.63,78,297,1,1,Poor,4,32.28,58.06,28.09,13.12\n18,16,Male,Undergraduate,3.44,3.74,2.29,4.32,0.49,6.75,6.21,60,134,1,1,Good,8,27.96,60.78,37.66,14.18\n19,20,Other,Postgraduate,5.08,1.57,1.82,3.75,1.74,6.23,8.47,85,56,1,0,Poor,2,13.74,54.29,24.66,6.54\n20,17,Other,Postgraduate,0.56,2.33,2.0,0.62,0.31,5.48,7.07,133,362,0,0,Poor,5,34.27,48.32,11.13,1.0\n21,23,Male,Undergraduate,9.31,4.04,3.06,1.46,1.23,7.74,2.9,71,118,1,0,Good,10,60.72,31.88,91.52,64.09\n22,19,Male,Undergraduate,4.5,2.2,2.14,1.24,0.0,4.42,10.82,134,179,1,0,Poor,2,19.46,62.09,20.88,1.0\n23,18,Female,Postgraduate,4.79,1.45,1.71,1.96,1.78,7.41,7.04,87,203,0,0,Good,10,42.45,28.98,62.96,33.52\n24,20,Male,High School,3.59,2.32,0.06,5.1,1.05,6.21,4.39,11,8,0,1,Poor,4,32.36,42.51,21.4,11.21\n25,23,Male,Postgraduate,7.44,2.36,1.64,2.77,1.39,6.84,2.92,22,293,0,1,Good,6,39.78,43.72,61.0,33.03\n26,18,Female,High School,5.77,2.02,1.1,3.9,1.54,6.98,8.58,57,160,1,0,Good,4,21.89,33.8,42.44,16.33\n27,20,Female,Postgraduate,4.64,2.85,1.53,2.19,2.27,5.9,3.66,33,151,0,0,Average,8,32.09,30.49,55.72,30.57\n28,24,Male,Undergraduate,7.3,2.05,3.02,5.01,0.16,7.51,10.48,51,182,0,0,Average,1,25.67,29.0,42.33,18.07\n29,16,Female,Postgraduate,3.59,4.07,2.85,2.57,2.47,7.7,5.91,101,214,0,1,Good,5,23.79,33.22,34.11,14.7\n30,23,Female,High School,3.54,2.39,2.67,5.24,1.22,5.91,4.89,38,325,1,0,Good,6,16.61,40.95,29.44,10.73\n31,25,Male,High School,3.95,2.45,2.53,3.97,0.72,5.9,6.69,139,4,0,1,Average,9,31.41,52.4,52.7,23.19\n32,19,Male,Postgraduate,5.52,2.41,0.0,3.91,0.26,8.16,11.43,95,306,1,1,Good,6,22.79,69.0,37.09,10.49\n33,20,Male,Postgraduate,4.68,2.18,2.65,2.85,0.54,6.49,6.03,12,235,1,0,Poor,1,25.48,44.61,19.89,11.53\n34,22,Male,Postgraduate,0.0,1.22,2.26,7.11,2.18,8.33,8.44,118,327,0,0,Average,6,7.26,20.37,3.39,1.0\n35,17,Other,Undergraduate,3.29,3.88,1.99,5.21,0.0,10.0,9.47,22,262,0,1,Poor,9,30.52,40.36,48.19,24.3\n36,21,Male,High School,2.6,2.99,2.43,2.71,2.53,4.7,3.65,113,85,1,0,Poor,8,24.24,38.06,37.5,22.18\n37,22,Other,Undergraduate,4.14,1.13,2.7,1.8,2.53,6.08,10.81,81,184,0,0,Poor,5,24.77,48.89,29.46,11.46\n38,18,Female,Undergraduate,5.94,0.47,3.15,2.45,2.62,6.74,6.18,119,395,1,1,Average,10,36.67,67.15,54.7,29.22\n39,17,Other,Undergraduate,3.29,3.92,1.06,3.61,0.46,7.31,3.56,106,326,0,1,Average,10,42.07,45.48,50.25,31.39\n40,24,Other,Postgraduate,3.58,4.91,2.06,4.25,0.0,6.92,6.73,67,25,1,1,Average,8,25.83,51.44,35.68,23.11\n41,19,Other,Postgraduate,4.06,3.41,2.46,1.9,0.79,6.52,4.91,127,179,0,0,Average,8,45.88,27.33,45.83,39.8\n42,21,Other,Postgraduate,0.53,2.89,1.89,1.52,3.52,7.47,8.45,2,346,1,1,Poor,4,12.74,52.2,1.0,1.0\n43,16,Other,High School,2.12,0.61,2.16,1.95,1.66,6.57,5.02,131,114,0,0,Poor,3,14.39,22.39,25.29,18.54\n44,18,Male,High School,2.59,2.33,2.86,2.13,1.55,7.18,8.42,33,168,0,1,Good,2,25.78,46.05,21.13,15.42\n45,22,Male,High School,7.29,3.51,1.56,6.04,0.0,7.53,9.71,108,69,0,0,Average,3,28.74,30.2,49.56,14.43\n46,18,Female,High School,7.24,2.22,1.6,3.7,2.39,5.93,6.58,139,50,1,0,Good,5,31.01,37.7,46.71,21.93\n47,20,Female,Undergraduate,5.66,2.71,2.42,2.45,3.89,7.74,6.54,128,48,1,1,Average,3,27.49,43.1,29.45,7.95\n48,20,Male,High School,4.73,0.71,2.8,4.93,2.1,6.68,5.94,141,166,0,1,Average,2,6.54,41.12,15.82,3.28\n49,22,Other,High School,4.14,2.22,1.53,3.58,0.0,7.56,6.66,124,381,0,1,Good,3,22.55,49.82,23.31,16.47\n50,19,Female,Undergraduate,6.14,2.62,2.25,2.36,0.0,7.07,6.6,68,14,1,0,Good,6,40.88,40.04,62.99,38.31\n51,16,Other,Postgraduate,2.29,3.85,2.97,4.0,1.1,6.12,7.09,118,309,0,1,Average,6,26.45,48.16,13.75,4.33\n52,22,Other,Undergraduate,6.8,1.4,4.26,5.88,0.0,6.73,7.25,131,247,1,0,Poor,2,23.45,30.69,45.1,26.65\n53,20,Female,Undergraduate,2.86,3.1,1.29,1.94,1.53,6.36,6.79,67,93,1,1,Poor,4,28.87,64.48,18.61,15.41\n54,23,Female,High School,4.56,0.0,2.18,6.37,2.51,5.95,11.87,105,173,1,0,Average,9,20.7,55.93,40.61,15.6\n55,22,Female,Postgraduate,6.94,0.34,0.26,3.01,1.33,5.29,6.28,130,207,0,0,Average,3,29.18,37.44,42.93,26.02\n56,23,Other,Undergraduate,2.1,1.94,1.29,0.0,0.58,5.78,7.18,105,273,0,1,Average,4,31.6,66.0,15.84,5.76\n57,17,Other,Undergraduate,1.97,4.43,2.65,0.0,1.3,5.26,10.49,75,327,1,0,Poor,9,35.02,67.82,32.16,1.0\n58,21,Male,High School,4.08,2.64,2.08,3.37,2.55,6.79,5.77,134,405,1,1,Good,10,42.23,61.42,48.76,23.74\n59,23,Female,Undergraduate,4.65,1.76,1.15,3.25,2.39,6.29,6.1,113,63,1,1,Average,1,13.62,47.62,23.81,10.13\n60,25,Male,Postgraduate,3.53,3.33,1.42,3.15,1.38,7.07,5.49,5,278,0,1,Good,9,39.46,49.23,39.34,22.49\n61,18,Other,Undergraduate,6.63,1.37,2.28,3.55,1.63,7.76,3.8,128,337,0,1,Average,2,32.9,32.52,42.01,26.34\n62,20,Male,Postgraduate,6.13,3.57,2.05,2.71,2.68,7.33,2.41,110,23,1,0,Good,2,22.34,35.07,28.39,8.36\n63,24,Other,Postgraduate,4.56,2.66,2.92,0.58,2.82,8.19,5.7,43,473,0,0,Average,9,45.86,27.85,65.02,40.11\n64,17,Male,Undergraduate,4.05,4.6,2.52,0.03,2.32,6.88,3.77,47,299,1,0,Average,2,29.45,38.16,20.45,10.05\n65,18,Male,High School,3.05,2.15,4.48,2.49,1.15,6.25,4.76,26,171,1,0,Good,1,13.54,43.27,17.14,1.0\n66,17,Female,Postgraduate,6.31,0.38,2.95,2.87,0.31,7.54,6.94,57,119,1,0,Good,8,34.49,22.37,56.05,25.53\n67,17,Male,High School,6.32,3.38,2.51,3.11,1.09,5.08,2.32,117,93,1,1,Poor,6,42.24,66.5,46.57,18.01\n68,19,Male,Undergraduate,4.5,2.66,2.37,1.01,1.09,9.18,6.38,76,302,1,0,Poor,1,29.04,27.5,35.08,23.12\n69,21,Female,High School,4.9,1.56,3.26,3.08,1.54,7.48,6.29,17,441,0,0,Poor,3,29.04,38.91,27.83,15.16\n70,25,Female,High School,2.27,2.75,0.0,1.24,2.81,6.92,3.68,97,244,1,1,Poor,7,31.7,61.19,20.69,12.34\n71,16,Other,Undergraduate,8.65,1.34,2.33,1.51,1.43,8.63,5.45,41,270,0,0,Poor,6,43.23,21.17,75.28,48.56\n72,24,Male,Postgraduate,5.69,4.16,0.87,2.69,1.24,6.32,5.94,40,84,1,0,Average,4,25.43,36.8,42.64,18.21\n73,17,Female,Undergraduate,7.55,3.95,3.31,2.03,3.44,7.4,7.56,148,414,1,1,Good,1,30.78,63.65,44.46,21.95\n74,22,Male,High School,5.53,3.05,4.04,0.55,2.05,7.29,6.32,70,89,1,1,Poor,1,33.88,52.24,29.89,18.02\n75,19,Other,High School,0.5,1.05,0.68,3.82,1.7,10.0,1.0,132,313,0,0,Good,6,11.17,10.42,25.38,14.5\n76,19,Male,High School,5.21,0.0,1.85,1.02,0.82,7.66,3.17,2,93,0,1,Good,4,21.89,37.07,31.25,16.13\n77,21,Male,Postgraduate,6.81,1.2,1.34,2.4,1.0,4.95,7.73,24,470,0,0,Poor,9,50.33,45.28,70.97,44.71\n78,25,Other,Postgraduate,2.78,2.04,1.49,3.87,0.68,9.29,10.91,87,456,0,0,Average,8,32.16,25.43,31.24,20.5\n79,23,Other,Postgraduate,3.76,0.78,0.79,4.21,0.0,6.99,7.71,85,453,1,0,Average,1,16.38,47.36,23.07,1.07\n80,25,Male,Postgraduate,4.22,3.31,1.52,1.43,0.0,7.43,8.74,41,187,1,0,Average,8,54.44,51.65,49.8,34.05\n81,18,Other,Undergraduate,5.69,2.27,0.0,2.93,3.94,7.11,11.02,28,200,0,0,Average,5,21.93,37.07,37.68,18.66\n82,19,Other,Undergraduate,3.4,3.27,1.3,4.21,1.96,8.95,9.85,134,163,1,0,Poor,1,7.28,34.14,8.31,1.0\n83,19,Other,Undergraduate,1.34,3.68,0.92,2.28,0.65,6.43,4.78,48,153,0,0,Average,2,22.99,23.83,12.52,5.59\n84,19,Other,Postgraduate,4.64,0.24,1.93,3.6,0.0,7.2,6.08,91,165,1,1,Poor,4,26.51,48.95,32.69,13.61\n85,24,Other,High School,1.24,4.08,1.28,1.91,2.06,9.74,3.47,56,110,1,1,Poor,8,39.96,38.65,28.36,24.91\n86,22,Other,High School,6.32,2.73,0.0,1.86,0.56,5.56,5.44,35,419,1,1,Good,4,29.22,67.75,39.64,15.82\n87,25,Female,Postgraduate,4.18,3.72,0.74,0.41,2.47,7.71,8.94,115,178,0,0,Good,2,22.56,30.24,33.13,7.94\n88,23,Other,Postgraduate,6.14,4.16,1.49,3.04,0.0,7.93,6.71,63,299,1,0,Average,4,39.69,35.67,40.46,26.92\n89,22,Female,Postgraduate,3.28,4.08,1.62,1.31,0.51,5.65,6.91,2,320,1,0,Good,1,20.83,49.26,19.22,7.68\n90,19,Other,Undergraduate,8.29,4.72,2.4,1.98,2.25,6.8,9.42,44,52,1,1,Good,2,25.75,62.19,33.98,15.98\n91,25,Female,Postgraduate,0.02,2.11,2.93,4.46,3.69,6.67,9.27,79,366,0,0,Average,2,10.16,40.66,1.0,1.0\n92,22,Male,Undergraduate,1.48,2.07,0.0,0.0,0.9,7.42,5.48,73,299,0,0,Good,7,33.95,13.38,41.01,22.94\n93,22,Other,High School,4.62,2.49,1.59,3.21,0.0,8.96,7.46,128,88,1,0,Good,7,44.31,31.53,66.46,45.2\n94,22,Female,High School,4.41,2.24,0.91,3.16,4.36,6.16,7.24,103,496,0,1,Poor,9,28.75,54.8,49.14,19.24\n95,17,Male,Undergraduate,5.62,2.31,2.26,2.69,2.2,9.8,13.42,40,440,1,0,Average,10,39.54,51.03,66.62,32.61\n96,19,Other,Undergraduate,4.38,2.46,0.21,5.14,2.55,9.81,6.02,67,233,0,0,Average,9,26.9,14.68,62.47,34.19\n97,20,Male,High School,6.37,3.86,3.24,2.75,0.0,7.44,8.77,100,487,1,0,Poor,3,28.83,47.42,31.59,16.97\n98,19,Male,Postgraduate,6.93,3.54,0.66,5.24,3.17,8.1,3.11,63,383,1,1,Average,6,43.45,44.77,61.38,34.72\n99,17,Other,Undergraduate,5.41,4.64,2.98,1.05,3.74,8.13,1.53,109,32,0,1,Poor,6,40.36,25.33,48.99,36.37\n100,16,Male,High School,4.5,2.63,1.72,2.99,1.65,8.87,1.0,47,149,1,0,Average,1,22.38,20.02,30.39,18.43\n101,21,Male,Undergraduate,6.71,3.71,0.07,4.72,3.62,6.87,4.38,87,460,0,0,Average,2,27.74,27.59,45.73,27.31\n102,24,Other,High School,2.89,2.3,2.09,0.08,3.14,7.86,9.66,108,98,1,0,Good,1,20.22,41.9,9.18,1.0\n103,22,Male,High School,3.24,2.53,0.35,4.87,0.0,9.46,10.35,55,180,1,1,Average,9,32.42,48.67,44.41,1.76\n104,24,Other,High School,2.95,2.01,3.05,0.41,1.7,7.9,7.35,112,211,1,1,Good,8,36.36,54.28,44.05,16.17\n105,25,Other,Postgraduate,0.89,0.0,2.72,2.3,0.77,8.75,2.99,94,69,1,1,Poor,2,10.48,31.9,1.0,1.0\n106,17,Male,High School,5.79,2.92,2.03,3.57,0.0,5.67,7.89,39,394,1,1,Average,6,37.14,69.23,46.81,16.7\n107,16,Other,Undergraduate,1.71,3.83,2.74,3.05,2.77,8.01,1.0,91,465,1,0,Average,7,25.5,34.61,27.85,16.5\n108,19,Male,High School,4.45,2.16,1.16,2.0,1.1,7.85,5.85,58,417,1,0,Poor,7,38.52,42.49,40.98,20.99\n109,17,Other,High School,2.48,3.52,0.83,5.1,1.16,7.76,7.98,139,287,1,0,Average,2,13.63,43.52,19.25,1.0\n110,19,Other,High School,3.25,1.55,2.07,2.99,1.87,6.52,7.64,8,239,0,1,Poor,2,17.92,60.5,3.81,1.0\n111,20,Female,High School,4.91,2.66,1.77,3.42,2.76,4.99,7.82,37,445,1,1,Good,3,6.8,71.79,24.27,1.0\n112,23,Other,Postgraduate,2.5,1.25,2.14,1.05,0.13,8.12,1.68,89,50,0,0,Good,1,25.21,15.74,22.28,20.45\n113,22,Male,High School,4.99,5.08,3.39,3.65,2.34,6.6,8.17,56,337,1,1,Average,5,30.26,68.72,34.82,12.47\n114,17,Other,Undergraduate,3.66,2.17,1.79,3.78,1.98,7.92,11.08,124,234,0,1,Good,9,41.73,41.69,49.48,24.97\n115,20,Other,Undergraduate,4.79,3.49,3.27,2.7,2.88,10.0,8.43,57,110,1,0,Poor,1,24.15,29.76,31.82,13.77\n116,19,Female,Undergraduate,5.09,4.23,1.93,0.05,2.7,5.53,6.6,12,93,0,0,Good,2,27.87,35.31,29.84,11.69\n117,19,Female,High School,2.42,2.84,0.66,1.52,0.46,8.2,7.19,38,471,1,1,Poor,7,33.78,64.61,24.11,12.37\n118,23,Other,Postgraduate,3.7,2.47,1.83,1.01,2.06,7.83,5.83,26,351,1,0,Poor,10,40.11,37.25,56.41,41.83\n119,22,Female,Postgraduate,5.05,0.98,1.07,3.12,1.33,9.33,6.38,16,80,1,1,Poor,10,30.92,32.5,56.08,34.13\n120,24,Female,Postgraduate,5.42,3.55,2.49,2.66,2.85,6.13,6.54,67,37,1,1,Poor,7,36.5,58.64,41.28,23.04\n121,22,Other,High School,5.65,2.32,2.44,3.49,3.28,7.96,10.24,60,271,1,1,Good,8,36.8,69.11,39.54,15.16\n122,20,Male,Postgraduate,3.7,1.66,1.26,3.13,2.86,6.98,11.16,11,161,1,0,Average,2,18.04,58.76,13.6,3.72\n123,20,Female,Postgraduate,2.77,2.23,2.4,5.34,1.02,7.47,6.08,18,26,1,1,Average,10,36.24,44.79,46.62,21.69\n124,23,Female,Undergraduate,2.62,5.4,1.75,0.66,0.81,7.2,6.32,57,74,1,1,Poor,7,44.66,51.04,48.11,34.56\n125,16,Female,High School,7.07,1.62,0.73,2.27,3.97,7.26,8.07,112,291,0,1,Good,7,36.67,54.24,50.21,29.7\n126,16,Other,High School,4.34,1.66,3.39,3.16,2.26,5.54,6.05,5,355,1,1,Good,9,24.86,70.76,39.76,8.35\n127,25,Female,Postgraduate,3.94,2.9,2.48,5.98,0.0,5.27,4.93,38,389,1,0,Poor,7,29.88,65.35,40.15,20.4\n128,24,Male,Undergraduate,3.95,3.25,1.58,3.62,0.31,8.73,6.69,99,94,0,1,Average,6,35.26,33.95,50.04,23.03\n129,24,Female,High School,4.98,2.13,1.68,4.96,2.84,5.54,7.54,5,295,1,0,Average,3,17.89,60.56,16.45,3.53\n130,20,Female,High School,3.04,3.41,1.29,3.81,1.34,8.58,9.03,76,44,1,0,Average,3,25.39,35.04,23.13,14.86\n131,24,Other,High School,8.04,4.67,1.44,4.44,0.89,8.0,3.76,43,290,1,1,Average,5,48.82,41.0,61.19,34.74\n132,22,Male,Undergraduate,3.8,1.7,2.65,3.8,1.12,6.8,7.4,145,275,1,1,Good,5,22.58,53.04,28.95,17.35\n133,17,Female,Undergraduate,3.91,3.69,1.94,4.06,1.43,6.02,7.31,33,483,1,1,Poor,2,22.55,65.94,12.98,7.26\n134,22,Female,Undergraduate,2.92,4.54,3.04,3.91,2.92,6.85,2.73,128,358,0,0,Average,7,32.57,12.87,42.1,42.34\n135,24,Other,Postgraduate,7.57,2.3,3.62,1.7,2.92,5.86,7.62,79,92,0,0,Good,4,31.73,37.7,48.98,24.08\n136,23,Male,Undergraduate,4.34,1.54,1.71,4.46,0.1,9.25,8.86,130,51,0,1,Average,5,38.69,26.79,50.82,31.56\n137,25,Other,Postgraduate,4.58,0.0,2.82,3.28,2.27,6.1,6.48,130,188,1,1,Average,1,17.48,59.44,15.49,1.0\n138,17,Other,Postgraduate,5.76,2.82,3.42,4.06,3.0,7.69,7.11,47,220,1,0,Poor,4,22.68,38.24,43.51,21.08\n139,23,Female,High School,2.81,1.56,2.17,3.58,1.8,7.91,3.92,121,190,1,1,Poor,5,20.29,40.53,27.67,25.52\n140,17,Male,Undergraduate,1.57,1.86,1.6,1.83,1.43,5.74,7.62,32,26,1,1,Good,7,26.5,71.68,19.01,3.69\n141,23,Other,Undergraduate,2.58,3.33,3.39,2.33,3.16,5.69,3.25,106,136,0,0,Average,10,29.18,27.37,41.41,29.57\n142,25,Other,Undergraduate,4.74,2.14,0.83,2.35,1.49,7.21,6.67,111,66,0,0,Average,5,30.41,18.57,39.86,22.45\n143,24,Male,High School,0.0,1.22,3.14,2.16,0.0,6.74,8.31,55,411,1,1,Average,10,21.65,63.74,23.36,8.04\n144,23,Other,Postgraduate,6.25,2.59,3.45,3.76,3.11,8.14,7.41,55,122,0,1,Poor,5,25.99,52.1,43.09,13.23\n145,17,Male,High School,5.69,2.67,3.15,1.67,0.5,6.39,5.78,133,128,0,0,Good,6,33.91,27.81,51.29,36.11\n146,19,Male,Undergraduate,1.92,0.0,3.39,2.13,1.41,6.51,5.95,84,220,0,0,Average,10,26.34,40.0,34.37,13.99\n147,17,Other,Postgraduate,4.29,3.53,2.7,4.55,1.17,6.08,7.31,127,45,0,1,Good,10,32.73,54.94,55.75,19.55\n148,24,Other,Undergraduate,2.81,3.12,2.65,5.99,1.53,6.02,9.02,66,68,0,1,Poor,9,25.07,56.01,26.22,18.61\n149,23,Other,High School,4.08,1.17,3.39,2.43,3.21,7.92,7.76,56,346,0,1,Average,10,27.91,47.62,40.45,21.84\n150,21,Other,Undergraduate,6.29,2.82,0.22,0.63,1.01,7.13,7.85,55,246,0,1,Average,9,48.35,53.2,57.65,32.1\n151,17,Female,Postgraduate,4.29,0.98,3.35,3.25,1.47,8.57,6.06,130,276,0,1,Good,6,32.15,41.06,35.66,19.23\n152,18,Male,High School,3.94,4.32,1.56,2.05,0.65,7.21,5.51,101,179,1,0,Average,9,40.41,42.56,51.51,32.14\n153,21,Other,Undergraduate,5.28,3.47,0.57,7.02,1.84,7.65,5.62,148,369,0,1,Good,6,25.66,25.72,51.44,26.69\n154,18,Other,Undergraduate,4.7,5.35,1.82,3.16,2.54,8.56,9.8,86,262,1,0,Poor,3,31.86,36.72,32.4,12.8\n155,18,Female,High School,3.93,2.87,1.37,4.15,2.19,4.0,7.85,55,30,0,1,Good,7,21.22,63.22,30.16,12.36\n156,25,Female,Postgraduate,5.13,1.48,1.75,0.0,0.0,5.64,5.82,35,147,0,1,Average,6,27.75,56.91,45.63,16.48\n157,19,Other,Postgraduate,3.22,3.29,0.87,4.05,2.56,7.54,11.51,149,10,0,1,Good,5,25.55,49.68,25.94,10.01\n158,18,Female,Postgraduate,5.0,4.91,2.47,5.03,1.6,7.71,8.02,135,138,1,1,Poor,2,24.99,47.77,28.55,5.14\n159,22,Female,Undergraduate,8.52,0.84,2.53,4.61,4.37,4.76,6.61,67,103,1,1,Average,7,34.94,61.81,56.58,31.95\n160,23,Male,Undergraduate,5.69,2.0,1.6,3.47,1.03,9.05,12.08,133,38,0,0,Poor,8,34.98,26.44,58.79,32.6\n161,25,Female,High School,5.73,2.2,1.59,1.14,2.98,7.01,5.37,107,402,1,0,Average,9,40.23,36.86,67.44,44.19\n162,17,Other,Postgraduate,3.58,4.15,2.47,2.84,1.32,7.28,5.08,24,82,0,0,Average,1,22.43,27.43,18.61,12.69\n163,19,Male,High School,4.13,2.96,1.57,3.74,0.0,9.33,6.98,53,273,1,1,Good,8,38.04,50.14,44.72,23.91\n164,24,Other,Postgraduate,6.75,1.94,1.79,1.85,0.0,7.84,6.37,10,225,0,0,Good,5,36.3,29.65,58.39,34.85\n165,19,Male,Postgraduate,3.63,3.2,0.22,2.64,0.64,8.33,3.36,71,496,1,1,Good,5,31.38,52.82,28.54,7.85\n166,23,Other,Undergraduate,4.35,2.94,0.0,4.9,0.77,7.56,3.71,17,41,1,0,Good,2,21.58,33.95,31.19,21.46\n167,25,Other,Postgraduate,5.89,1.44,2.86,1.91,2.75,7.17,7.1,127,94,1,0,Average,9,35.21,50.48,57.96,44.12\n168,25,Female,Postgraduate,4.65,2.29,2.65,3.45,1.79,6.06,6.86,125,75,0,1,Good,9,31.47,46.54,47.51,30.46\n169,19,Male,Postgraduate,5.81,1.78,1.46,4.34,1.49,6.9,7.77,66,53,1,0,Good,1,16.5,45.32,32.89,9.84\n170,19,Female,Postgraduate,5.21,3.4,1.38,2.99,3.14,8.3,11.51,46,353,0,0,Good,7,35.02,38.42,48.42,29.39\n171,21,Other,Postgraduate,3.01,2.68,3.74,1.28,0.16,5.89,8.79,82,430,1,1,Average,3,32.54,67.14,16.09,2.27\n172,22,Other,High School,6.47,4.01,0.6,3.82,3.16,8.25,6.38,86,245,1,0,Average,4,35.54,33.16,50.18,30.72\n173,16,Other,Undergraduate,2.72,0.78,3.49,3.5,0.0,6.23,8.28,149,380,1,1,Average,10,38.28,67.06,46.57,28.2\n174,24,Other,High School,9.38,1.33,1.11,1.21,0.67,7.4,8.11,89,375,1,0,Poor,6,45.6,45.73,71.16,34.63\n175,23,Female,Undergraduate,5.72,0.95,1.18,2.38,1.66,10.0,4.57,97,148,1,0,Poor,6,33.57,8.43,58.3,46.93\n176,23,Female,Postgraduate,4.4,1.49,0.77,6.35,0.0,6.73,6.36,78,295,1,0,Poor,4,19.95,39.38,36.51,10.27\n177,20,Other,High School,4.12,3.24,0.76,2.24,0.23,6.28,8.92,84,457,1,1,Average,6,29.55,68.36,28.78,12.2\n178,20,Male,Undergraduate,4.13,1.97,2.4,4.55,0.85,6.45,8.72,83,87,1,0,Poor,1,16.02,48.6,14.52,6.2\n179,21,Male,Postgraduate,1.02,0.01,2.37,2.11,0.28,7.68,7.82,134,242,0,0,Good,2,15.57,21.92,13.63,16.45\n180,16,Other,Postgraduate,5.96,0.48,2.06,2.31,1.95,7.83,2.75,84,331,0,1,Good,5,29.0,35.87,54.15,28.91\n181,24,Male,Postgraduate,4.12,4.35,0.72,4.68,0.0,7.38,4.44,12,171,1,0,Average,5,27.61,36.55,34.26,15.33\n182,25,Male,High School,5.16,3.13,1.77,1.18,2.42,10.0,3.5,123,24,1,0,Poor,4,44.34,14.26,48.61,35.45\n183,18,Female,Undergraduate,3.45,2.6,1.23,2.45,2.19,6.35,7.67,122,94,1,1,Average,4,31.24,55.6,27.92,16.2\n184,21,Female,Postgraduate,4.31,1.4,2.68,2.58,0.87,8.8,8.88,54,39,0,1,Good,7,41.43,32.86,40.77,27.48\n185,17,Female,Undergraduate,3.43,3.64,1.41,2.52,1.76,6.86,6.06,89,334,1,1,Average,9,29.0,45.78,48.8,23.68\n186,21,Other,High School,5.61,2.94,0.95,1.73,1.11,8.77,4.11,38,238,1,1,Poor,10,44.81,45.01,60.78,26.73\n187,25,Other,Undergraduate,8.15,3.39,2.22,4.82,1.62,5.51,8.79,129,298,0,0,Average,1,33.31,36.68,51.83,26.96\n188,18,Other,High School,4.44,3.03,0.72,4.84,0.94,7.47,4.5,27,456,1,1,Average,8,33.86,60.84,42.53,15.86\n189,20,Other,Postgraduate,4.59,1.12,0.0,3.51,2.28,6.42,5.91,86,99,1,1,Good,5,14.28,60.53,29.62,1.3\n190,19,Other,Postgraduate,3.64,2.86,1.87,3.51

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
from sklearn.datasets import make_regression

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [37]:
df = pd.read_csv(r'/content/C:\Users\A20405224099\Downloads\Multiple Regression\ultimate_student_productivity_dataset_5000.csv/ultimate_student_productivity_dataset_5000.csv')
df.head()

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,Good,3,15.92,37.00,13.70,1.00
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,Good,8,27.39,34.37,45.15,18.30
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,113,480,1,1,Poor,3,22.31,77.31,20.92,9.37
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,Good,8,38.11,39.53,59.23,27.81

In [44]:
df = pd.DataFrame({'study_hours':X[:,0],'self_study_hours':X[:,1],'exam_score':y})

In [45]:

df.shape

(100, 3)

In [46]:
df.head()

   study_hours  self_study_hours  exam_score
0    -0.411644         -0.086801  -77.140666
1    -0.505772          0.330292  -13.704516
2     0.492676          1.487480  127.569147
3    -0.442056         -0.481236 -127.422646
4     0.968299          0.005545  126.209214

In [47]:
fig = px.scatter_3d(df, x='study_hours', y='self_study_hours', z='exam_score')

fig.show()

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
lr = LinearRegression

In [25]:
lr.fit(X_train,y_train)

LinearRegression()

In [49]:
y_pred = lr.predict(X_test)

In [50]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 36.174302667567574
MSE 2250.082600674489
R2 score 0.8225191625060533

In [56]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)
final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

z_final = lr.predict(final).reshape(10,10)

z = z_final

In [57]:
fig = px.scatter_3d(df, x='study_hours', y='self_study_hours', z='exam_score')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [58]:
lr.coef_

array([60.88675281, 57.25690484])

In [59]:
lr.intercept_

np.float64(7.250388722099535)